#!/bin/sh

DOWNLOAD_TARGET=${1:-$DOWNLOAD_TARGET}
DOWNLOAD_URL=${2:-$DOWNLOAD_URL}

if [ -n "$DOWNLOAD_TARGET" ] && [ -n "$DOWNLOAD_URL" ] && [ ! -e "$DOWNLOAD_TARGET" ] ; then
  wget -O "$DOWNLOAD_TARGET" $DOWNLOAD_OPTIONS "$DOWNLOAD_URL"
fi
